SF:lib\core\errors\failure.dart
DA:7,0
DA:12,0
DA:13,0
DA:17,0
LF:4
LH:0
end_of_record
SF:lib\core\use_cases\use_case_with_params.dart
DA:4,1
LF:1
LH:1
end_of_record
SF:lib\core\use_cases\use_case_without_params.dart
DA:4,1
LF:1
LH:1
end_of_record
SF:lib\src\authentication\data\models\user_model.dart
DA:8,2
DA:15,1
DA:16,0
DA:23,1
DA:24,1
DA:25,1
DA:26,1
DA:27,1
DA:28,1
DA:31,0
DA:32,0
DA:35,0
DA:41,0
DA:42,0
DA:43,0
DA:44,0
DA:45,0
DA:49,0
DA:50,0
DA:51,0
DA:52,0
DA:53,0
DA:54,0
DA:58,0
LF:24
LH:8
end_of_record
SF:lib\src\authentication\domain\entities\user.dart
DA:9,3
DA:16,1
DA:17,0
DA:24,1
DA:25,4
LF:5
LH:4
end_of_record
SF:lib\src\authentication\domain\use_cases\create_user.dart
DA:8,1
DA:10,1
DA:12,2
DA:13,1
DA:14,1
DA:15,1
DA:25,1
DA:31,1
DA:32,0
DA:38,0
DA:39,0
LF:11
LH:8
end_of_record
SF:lib\src\authentication\domain\use_cases\get_users.dart
DA:6,1
DA:8,1
DA:9,2
LF:3
LH:3
end_of_record
SF:lib\main.dart
DA:4,0
DA:5,0
DA:17,2
DA:19,1
DA:21,1
DA:22,0
DA:23,0
DA:26,0
DA:27,0
LF:9
LH:3
end_of_record
